name: My first workflow

on: [push, pull_request]
jobs:
  job_1:
    name: My first job
    runs-on: ubuntu-latest
    steps:
    - name: my first step
      uses: actions/checkout@v2
      
    - name: python in one code
      uses: actions/setup-python@v5.1.0

    # - name: run python
    #   run: python myapp.py
    #   shell: bash
        
    - name: my second step
      run: echo "Hello world"
      shell: bash

    - name: my third step
      run: |
        echo "first hello"
        echo "second hello"
        shell:bash

    - name: The job has succeded
      if: ${{success(}}
      run: echo "successfully" 
  # deploy: 
